### ISSUE TITLE
切换慢这个问题如何解决啊？

### ISSUE THREAD

**Issue by e20999** [HTWMedia/HTV#13]
换个台要等5秒以上，整体感觉是太慢了。
恳望解决。

**Comment by HTWMedia** [comment]
是哪个地区，我更新下源。和tv源及使用者带宽、播放设备有关。

**Comment by e20999** [comment]
> 是哪个地区，我更新下源。和tv源及使用者带宽、播放设备有关。

四川移动。谢谢。
