### ISSUE TITLE
部分台显示为绿色花屏

### ISSUE THREAD

**Issue by miaoyuwelcome** [HTWMedia/HTV#15]
有声音，就是绿花屏，1台正常，能否加入更换编码格式

**Comment by HTWMedia** [comment]
花屏可能是刚进入的时候会闪一下，这是为硬件加速做的缓存，是源不太好的情况下出现的，一般闪过之后就好了。时间比较长的话很可能是源的问题，不是本地的源，或者是源比较卡，网速卡等。编解码用的是ffmpeg，常见的编码的格式都是支持的。可以退出再重新进，会自动切换源。

**Comment by miaoyuwelcome** [comment]
> 花屏可能是刚进入的时候会闪一下，这是为硬件加速做的缓存，是源不太好的情况下出现的，一般闪过之后就好了。时间比较长的话很可能是源的问题，不是本地的源，或者是源比较卡，网速卡等。编解码用的是ffmpeg，常见的编码的格式都是支持的。可以退出再重新进，会自动切换源。

我在试试，感谢解答
