### ISSUE TITLE
画面播放卡顿、有马赛克、推送的自定义直播源链接无效

### ISSUE THREAD

**Issue by wwb521** [HTWMedia/HTV#2]
![c113b75b277ffd32cb669cc63e91170](https://github.com/HTWMedia/HTV/assets/58287307/1358b008-6611-406a-8fe9-5d864703f802)

**Comment by wanminny** [comment]
+100 卡成不可用！

**Comment by HTWMedia** [comment]
目前app源针对湖北联通调优，请告知下地区，更新下源。自定义源目前不支持，方便的话发下源，我可以给加上去。

**Comment by mnigc** [comment]
> 目前app源针对湖北联通调优，请告知下地区，更新下源。自定义源目前不支持，方便的话发下源，我可以给加上去。

我在浙江杭州，电信网络，能正常看，但是还是有点卡，感谢作者贡献~

**Comment by jun9** [comment]
浙江衢州，移动网络，大部分显示 I/O Error， 个别卡到无法看

**Comment by gc89925** [comment]
换台卡，进去就好了，显示都正常，武汉地区

**Comment by HTWMedia** [comment]
开放了源获取API，可以在其它播放器中使用。
