### ISSUE TITLE
退出应用后后台依然播放声音

### ISSUE THREAD

**Issue by ilusoiluso** [HTWMedia/HTV#20]
正常按2次返回退出后，依然后台在播放

**Comment by HTWMedia** [comment]
可能是IPTV源有些卡顿，退出时销毁资源比较慢，稍等一会就完全退出了。

**Comment by kicklie** [comment]
一直会在后台播放。就算是打开另一个视频播放器，它也不会自动关闭。很是郁闷。

还有一个问题，安装后找不到图标。应用列表里面也看不到。
我现在想卸载都不知道咋办了。

**Comment by kicklie** [comment]
同样的问题也遇到了。
