### ISSUE TITLE
源可以参考灵犀直播的，他比较全，地方台三沙卫视之类的都有。

### ISSUE THREAD

**Issue by ashsteins** [HTWMedia/HTV#5]
源可以参考灵犀直播的，他比较全，地方台三沙卫视之类的都有。

**Comment by HTWMedia** [comment]
这些源也都有，只不过每个地区的源不一样，基本的央视和卫视都是有的，然后各个地方有不同的地方台。另外还可以根据关键字搜台，这些自定义功能没放上来。
