### ISSUE TITLE
请问这个支持多线路吗？【另报告花屏、黑屏、无声音】

### ISSUE THREAD

**Issue by 4yt1k** [HTWMedia/HTV#7]
我自己维护了一个源，在tvbox配置之后，播放很流畅，有ipv6也有ipv4的。
我推送自定义源成功之后，使用HTV播放，要么花屏，要么黑屏，声音则直接全都没有，基本没有可以正常播放的频道。

我看很多人反映卡顿，我这是连卡顿的资格都没有啊:(

作者做这个APP的思路很好，我就想要一个简单、稳定、能开机启动，可以在安卓4.4上安装的直播软件，给老人使用，当然能自定义源更好。

mytv的问题是频道不全，还有就是三天两头出问题，期待作者能继续完善，超过mytv。

**Comment by HTWMedia** [comment]
目前发布的app不播放自定义推送的源，请问你是哪个地区的卡顿？

**Comment by 4yt1k** [comment]
> 目前发布的app不播放自定义推送的源，请问你是哪个地区的卡顿？

原因貌似找到了，显示启用了自定义源，实际上使用的还是内置的源。
另外，在看到你回复之前，我为了确认是不是多线路的原因，特意制作了一个单源的m3u，症状跟多线路源是一样的。
我是广西电信。

**Comment by 4yt1k** [comment]
> 目前发布的app不播放自定义推送的源，请问你是哪个地区的卡顿？

对了，请问怎么在模拟器里打开设置界面？

**Comment by HTWMedia** [comment]
模拟器里双击屏幕打开设置，单击选台。

**Comment by 4yt1k** [comment]
> 模拟器里双击屏幕打开设置，单击选台。

谢谢！
不太会用模拟器，我装的是蓝叠，怎么也找不到跟网络有关的设置。
HTV在模拟器里提示通过http://10.0.2.15:10381进行自定义源配置，但这个IP电脑是无法访问的。

**Comment by HTWMedia** [comment]
不用配置自定义源，不会显示在播放列表，也不会播放的。

**Comment by 4yt1k** [comment]
> 不用配置自定义源，不会显示在播放列表，也不会播放的。
我在机顶盒上自定义了直播源的，APP显示已经启用，但实际上没有启用，就想在模拟器上再测试一下。

**Comment by HTWMedia** [comment]
app启用了硬件加速，模拟器可能没有这个能力，模拟器上的Android系统可能也不完整，所以可能播放不了或卡顿。

**Comment by 4yt1k** [comment]
> app启用了硬件加速，模拟器可能没有这个能力，模拟器上的Android系统可能也不完整，所以可能播放不了或卡顿。

你可能误解了我的意思。
我是说在机顶盒【安卓4.4】上无法播放，然后我到模拟器里测试，结果都一样。
刚才我直接安装到小米电视里，还是一样的结果，就是自定义源已经推送成功了，APP里也显示自定义源已经启用，但实际上APP使用的还是内置的直播源。

而内置源在我这里无法播放。。。

我用机顶盒是因为小米电视不给设置指定的开机启动APP，老人就想按一下按钮就进入电视直播画面。
上下左右返回确定什么的，对我家的老人来说太复杂了。
=================================
我终于找到了一个理想的直播软件，极悦直播！！！
无广告频道、干净、稳定、速度快、可以开机启动、支持安卓4.4及以上。
从现在起正式抛弃mytv！！！
==================================
折腾到这有点感慨，mytv跟tvbox一样，被称作神器，实际情况是频道不全不说，还三天两头出问题，连给用户正常使用都做不到，不明白怎么成为神器的。
